# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bridge <- function(y, X, prior, a = 0.5, b = 0.5, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE) {
    .Call('_shrinkage_bridge', PACKAGE = 'shrinkage', y, X, prior, a, b, mcmc, burnin, thin, verbose)
}

.bgridge <- function(y, X, g, prior, a = 0.5, b = 0.5, c = 1, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, light = TRUE) {
    .Call('_shrinkage_bgridge', PACKAGE = 'shrinkage', y, X, g, prior, a, b, c, mcmc, burnin, thin, verbose, light)
}

