# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ridge <- function(y, X, prior, a = 0.5, b = 0.5, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE) {
    .Call('_shrinkage_ridge', PACKAGE = 'shrinkage', y, X, prior, a, b, mcmc, burnin, thin, verbose)
}

.ridge_fixed <- function(y, X) {
    .Call('_shrinkage_ridge_fixed', PACKAGE = 'shrinkage', y, X)
}

.gridge <- function(y, X, g, prior = 1L, a = 0.00001, b = 0.00001, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, step = 1000L) {
    .Call('_shrinkage_gridge', PACKAGE = 'shrinkage', y, X, g, prior, a, b, mcmc, burnin, thin, verbose, step)
}

.sgridge <- function(y, X, g, priors, a = 0.00001, b = 0.00001, c = 0.00001, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, step = 1000L) {
    .Call('_shrinkage_sgridge', PACKAGE = 'shrinkage', y, X, g, priors, a, b, c, mcmc, burnin, thin, verbose, step)
}

.gd <- function(y, X, g, prior = 1L, a = 0.00001, b = 0.00001, c = 1, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, step = 1000L) {
    .Call('_shrinkage_gd', PACKAGE = 'shrinkage', y, X, g, prior, a, b, c, mcmc, burnin, thin, verbose, step)
}

