# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fast_svd <- function(X) {
    .Call('_shrinkage_fast_svd_list', PACKAGE = 'shrinkage', X)
}

.get_brg_opt_tauminus2 <- function(y, X) {
    .Call('_shrinkage_brg_eb_tauminus2', PACKAGE = 'shrinkage', y, X)
}

.brg_gibbs <- function(y, X, prior, a = 0.5, b = 0.5, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, bp = 1L) {
    .Call('_shrinkage_brg_gibbs', PACKAGE = 'shrinkage', y, X, prior, a, b, mcmc, burnin, thin, verbose, bp)
}

.brg_closedform <- function(y, X, fixed = FALSE, tau2 = 1) {
    .Call('_shrinkage_brg_closedform', PACKAGE = 'shrinkage', y, X, fixed, tau2)
}

.brl_gibbs <- function(y, X, g, prior = 1L, a = 0.00001, b = 0.00001, mcmc = 1000L, burnin = 1000L, thin = 10L, verbose = TRUE, bp = 2L) {
    .Call('_shrinkage_brl_gibbs', PACKAGE = 'shrinkage', y, X, g, prior, a, b, mcmc, burnin, thin, verbose, bp)
}

